nginx:
  nameOverride: sow-rest
  service:
    type: NodePort
  serverBlock: |-
    server {
        listen 0.0.0.0:8080;
        client_max_body_size 0;
        location / {
            proxy_pass http://sow-rest-ui/;
        }
        location /api {
            proxy_pass http://sow-rest-api;
        }
    }
sow-rest-ui:
  image:
    registry: k8serviceaccount
    repository: k8-rebuild-file-drop
    imagePullPolicy: Never
    tag: main-c6db7c2
